{
 "title": "Trilyzer",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TricountId",
    "query": "SELECT concat(title,'|' ,tr_uuid )\nFROM public.tricount;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "readMe",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Trilyzer\n\n[Add a new tricount](http://grafana.trilyzer.com:9090/)\n\n# Trilyzer code\nhttps://github.com/RomainMichau/tricount_analyzer\n\nMoney transfer are ignored in these stats"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total expense cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n sum(amount_tr_currency)\nFROM expenses\nWHERE\n  $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Number of expenses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n count(amount_tr_currency)\nFROM expenses\nWHERE\n  $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Expenses over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  addeddate AS \"time\",\n  amount_tr_currency as \" \",\n  Name as \"bruh\"\n  \nFROM expenses e JOIN tricount t on t.tr_uuid = e.tr_uuid\nWHERE\n  $__timeFilter(addeddate) and e.tr_uuid = '$TricountId'\n\nORDER  BY \"time\"\n"
    }
   ]
  },
  {
   "title": "Expenses over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  addeddate AS \"time\",\n  amount_tr_currency as \"cost\"\n\nFROM expenses e JOIN tricount t on t.tr_uuid = e.tr_uuid\nWHERE\n  $__timeFilter(addeddate) and e.tr_uuid = '$TricountId'\n\nORDER  BY addeddate\n"
    }
   ]
  },
  { "title": "Expenses per period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Expenses cost per month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('month',addeddate) AS \"time\",\n  sum(amount_tr_currency) as \"Total\"\nFROM expenses\nWHERE\n  $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\ngroup by \"time\";"
    },
    {
     "rawSql": "SELECT\n  DATE_TRUNC('month',addeddate) AS \"time\",\n  sum(i.amount_tr_currency) as expense, i.\"User\"\nFROM expenses e Join impacts i on i.exp_uuid = e.exp_uuid\nWHERE $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\ngroup by \"time\", \"User\" order by \"time\";"
    }
   ]
  },
  {
   "title": "Expenses per year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('year',addeddate) AS \"time\",\n  sum(amount_tr_currency)\nFROM expenses\nWHERE\n  $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\ngroup by \"time\";"
    },
    {
     "rawSql": "SELECT\n  DATE_TRUNC('year',addeddate) AS \"time\",\n  sum(i.amount_tr_currency) as expense, i.\"User\"\nFROM expenses e Join impacts i on i.exp_uuid = e.exp_uuid\nWHERE $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\ngroup by \"time\", \"User\" order by \"time\";"
    }
   ]
  },
  {
   "title": "Total expenses cost per user",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n  sum(i.amount_tr_currency) as expense, i.\"User\"\nFROM expenses e Join impacts i on i.exp_uuid = e.exp_uuid\nWHERE $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\ngroup by \"time\", \"User\" order by \"time\";"
    }
   ]
  },
  {
   "title": "Number of expenses per user",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    1 AS \"time\",  count(i.amount_tr_currency) as \"nb of expenses\", i.\"User\"\nFROM expenses e  Join impacts i on i.exp_uuid = e.exp_uuid\nWHERE $__timeFilter(addeddate) AND tr_uuid = '$TricountId'\ngroup by \"User\""
    }
   ]
  }
 ]
}